ci: Trying to fix release pipeine
- concerning tmp token creation

diff --git a/.github/workflows/jenkins-release.yml b/.github/workflows/jenkins-release.yml
--- a/.github/workflows/jenkins-release.yml
+++ b/.github/workflows/jenkins-release.yml
@@ -80,6 +80,13 @@ jobs:
         uses: actions/download-artifact@v6
         with:
           path: target/
+      - name: Validate private key exists
+        run: |
+          if [ -z "${{ secrets.GH_TMP_TOKEN_PRIVAT_KEY }}" ]; then
+            echo "Private key missing"
+            exit 1
+          fi
+          echo "Private key loaded (not printing)"
       - uses: actions/create-github-app-token@v2
         id: app-token
         with:
